spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&amp;serverTimezone=GMT&amp;useSSL=false"
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: warn
    com.grbk: info
  file: log/blog-pro.log
server:
  port: 8081
